[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"


# =====================
# REDIRECTS
# =====================

[[redirects]]
from = "http://stemxlearning.in/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.stemxlearning.in/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://stemxlearning.in/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.stemxlearning.in/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://stemxlearning.com/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.stemxlearning.com/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://stemxlearning.com/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.stemxlearning.com/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true
