[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"


# =====================
# REDIRECTS
# =====================

[[redirects]]
from = "http://stemxlearing.in/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.stemxlearing.in/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://stemxlearing.in/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.stemxlearing.in/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://stemxlearing.com/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.stemxlearing.com/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://stemxlearing.com/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.stemxlearing.com/*"
to = "https://www.stemxlearning.com/:splat"
status = 301
force = true
