[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# =====================
# REDIRECTS
# =====================

[[redirects]]
from = "http://stemixlearning.in/*"
to = "https://www.stemixlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://stemixlearning.in/*"
to = "https://www.stemixlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://stemixlearning.com/*"
to = "https://www.stemixlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://stemixlearning.com/*"
to = "https://www.stemixlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://stemexlearning.com/*"
to = "https://www.stemixlearning.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://stemexlearning.com/*"
to = "https://www.stemixlearning.com/:splat"
status = 301
force = true
